---

services:
  rasa:
    build:
      context: ./rasa
      dockerfile: Dockerfile
    volumes:
      - ./rasa:/app
    environment:
      - LANG=C.UTF-8
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: rasa run --enable-api --cors "*"

  web:
    image: nginx:1.27.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./website:/usr/share/nginx/html
    depends_on:
      - rasa
